<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Nasional</name>
   <tag></tag>
   <elementGuidId>d5112f43-23e0-4a0d-96e8-11b2daaf04cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radix-_r_ni_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Internasional'])[2]/following::span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Nasional&quot;s >> internal:text=&quot;Nasional&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>226d3bae-3db0-4117-9b88-efa22dc30412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-_r_ni_</value>
      <webElementGuid>55e05541-6f87-422a-87af-103bacae4f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nasional</value>
      <webElementGuid>0e0be5a7-f436-4d12-bc10-98dbb0194387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-_r_ni_&quot;)</value>
      <webElementGuid>168ff4d3-009f-492e-8bda-fe6db6f83f05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='radix-_r_ni_']</value>
      <webElementGuid>ee575746-cf2c-4ad9-a7bf-48092d652243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-_r_mp_']/div/div[2]/span[2]</value>
      <webElementGuid>976f4b4e-e3d4-4526-8d68-e43dc1055938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Internasional'])[2]/following::span[2]</value>
      <webElementGuid>c6234a7e-8338-49d1-9f69-468314ad4380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DIKLN'])[2]/preceding::span[2]</value>
      <webElementGuid>a618bebe-3cbe-4a47-8aec-66673a68b2e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[2]</value>
      <webElementGuid>462ee1ee-f119-489f-ba9b-fa7c94844bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'radix-_r_ni_' and (text() = 'Nasional' or . = 'Nasional')]</value>
      <webElementGuid>53ef0a10-bab4-463d-b9c5-73ea6b79b82f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
