<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>combobox kursusa</name>
   <tag></tag>
   <elementGuidId>7bfb6cc9-d31a-4fbb-9073-87e14d0f4718</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radix-_r_bi_']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@placeholder = 'Cari Kursus - Angkatan' and @role = 'combobox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radix-_r_bi_</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Cari Kursus - Angkatan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42d58462-bfb8-436f-bb7e-2c5357170624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>command-input</value>
      <webElementGuid>29a23861-d0fd-45d6-833a-aa042332fb8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>placeholder:text-muted-foreground flex w-full rounded-md bg-transparent py-3 text-[93.75%] outline-hidden disabled:cursor-not-allowed disabled:opacity-50 h-9</value>
      <webElementGuid>dc57f80f-e582-4396-8877-f98fc197e323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari Kursus - Angkatan</value>
      <webElementGuid>04c6f302-f380-4a66-a9b7-8ca9294ef242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>45032be3-c8a4-43e5-858c-bd416cba0b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>29a8c80e-f210-4800-bf98-bdc949ae7d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c51e9bee-5a1d-4e5f-b48d-3c2d07cbb465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>eec9e0cc-5490-46ac-a775-6a9b3ddcf1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>f9efa73d-aa31-41e6-b219-c9f9dbbcc7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>61b9b1e2-b0cb-42c1-b05d-762cf1367148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-_r_bg_</value>
      <webElementGuid>9e2554ac-4ee1-484f-bd21-94036631a17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>radix-_r_bh_</value>
      <webElementGuid>82e0a252-2244-4940-b81d-310bcb38c426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-_r_bi_</value>
      <webElementGuid>64c4cdce-bc2e-41d5-9650-848bfb795e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>311b4c5e-b170-4f0d-83e9-fbd0ad3d8d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>`</value>
      <webElementGuid>73733f24-8569-4c92-9de9-3720e4235fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-_r_bi_&quot;)</value>
      <webElementGuid>dc91fd8b-6728-420d-9a04-d6ad9e439883</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radix-_r_bi_']</value>
      <webElementGuid>25cf64fa-4abd-44ef-b24e-66d43a7430f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-_r_b6_']/div/div/input</value>
      <webElementGuid>04f78841-ec2a-40ce-82fc-572f442b56d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>a28ed71e-70e1-48db-abe2-d454f15260d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Cari Kursus - Angkatan' and @id = 'radix-_r_bi_' and @type = 'text']</value>
      <webElementGuid>b395c77a-d52a-427e-b828-2967e32734a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
