<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_0 Filter yang diterapkan</name>
   <tag></tag>
   <elementGuidId>6c51efd4-66c1-4453-809c-7c4bc311275d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div/div[1]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.items-center.justify-between.gap-3 > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-_r_8b_']/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;0 Filter yang diterapkan&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c087d68a-0138-43f7-9518-9e30565bd56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0 Filter yang diterapkan</value>
      <webElementGuid>75548833-7f60-43ef-ab0a-f22cef397872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div/div[1]/p</value>
      <webElementGuid>2f0b3404-0a19-457e-a17d-65efceab452c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-_r_8b_']/div/p</value>
      <webElementGuid>96fe6031-418e-4e39-abe2-2e29aba19c32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::p[1]</value>
      <webElementGuid>4e5f373c-f038-4d77-b54b-ddb335eb3140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus Filter'])[1]/preceding::p[1]</value>
      <webElementGuid>86e5e6cc-1cd0-4919-bc44-51bcb74b6137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kursus - Angkatan'])[3]/preceding::p[2]</value>
      <webElementGuid>a4f56659-d44e-4f10-977a-8083dc5cb959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0 Filter yang diterapkan']/parent::*</value>
      <webElementGuid>83b43549-28b9-4f1c-9159-311179bc7c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/p</value>
      <webElementGuid>b2370bfb-23b3-4434-859c-1c587e7f34ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '0 Filter yang diterapkan' or . = '0 Filter yang diterapkan')]</value>
      <webElementGuid>34fc1a05-ba92-4ad1-951d-8423b51e3bb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
