<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tanggal Ujian</name>
   <tag></tag>
   <elementGuidId>1a132f32-a538-4f38-b68a-7499354c21bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='date']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.truncate.opacity-60</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Date picker&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fcfb9519-2c80-4be0-b278-41a740e8396f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>truncate opacity-60</value>
      <webElementGuid>981c863f-a1c8-4fd3-a8e3-28923998b441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tanggal Ujian</value>
      <webElementGuid>8f4ba331-8bab-4199-8b21-2733db778148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;date&quot;)/span[@class=&quot;truncate opacity-60&quot;]</value>
      <webElementGuid>2fb34b31-9a7b-4255-a6dd-6c56b88a8994</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='date']/span</value>
      <webElementGuid>0e71d95c-6df9-49fd-a21f-387cb06d0445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Ujian'])[1]/preceding::span[2]</value>
      <webElementGuid>f2a253d9-69f2-4914-b63c-378aa184a7ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/span</value>
      <webElementGuid>f6c5647c-3490-4884-8af2-b684d51f0744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tanggal Ujian' or . = 'Tanggal Ujian')]</value>
      <webElementGuid>66bb0c04-f555-4651-aad5-f900b15d86a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
