<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pendaftaran</name>
   <tag></tag>
   <elementGuidId>2d026d3a-1a4f-4285-bcee-37d62a65d1fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='radix-_r_fd_']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Pendaftaran&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7031d805-75df-4241-b262-8aba828f2e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>[[data-collapsible][data-state=collapsed]_&amp;]:opacity-0</value>
      <webElementGuid>d65bf900-a714-435b-b3e8-c38575a254da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pendaftaran</value>
      <webElementGuid>3c04b34b-0443-4c3a-a534-f9ba9c7310bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-_r_fd_&quot;)/span[@class=&quot;[[data-collapsible][data-state=collapsed]_&amp;]:opacity-0&quot;]</value>
      <webElementGuid>6575e78d-92b4-44a2-8331-5717b118c09e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='radix-_r_fd_']/span</value>
      <webElementGuid>6ddbea48-5253-4a19-b08f-c98112c4339e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profil Siswa'])[1]/following::span[1]</value>
      <webElementGuid>f9d2890b-6524-49f2-8474-1adf066600eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profil Calon Siswa'])[1]/following::span[2]</value>
      <webElementGuid>22ba0afd-a2db-4c06-a5ca-09c8186944de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manajemen'])[1]/preceding::span[1]</value>
      <webElementGuid>4635c67a-4a3c-4945-9bdc-57d02f5b0408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SU'])[1]/preceding::span[2]</value>
      <webElementGuid>c2510492-2e10-4575-b832-1d2e51131978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pendaftaran']/parent::*</value>
      <webElementGuid>fc62298f-e978-4b74-8002-44e15b176e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/button/span</value>
      <webElementGuid>f50facf4-efe7-4a0e-be9f-142a1316fc80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Pendaftaran' or . = 'Pendaftaran')]</value>
      <webElementGuid>1802275d-6b54-4dde-b2d6-0318a86b31b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
