<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select item kursus</name>
   <tag></tag>
   <elementGuidId>2dfcc029-374e-409b-a17b-ed81f146515a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='courseIntention']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.overflow-hidden.opacity-60</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Minat Kursus*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fa98a670-278e-4c7a-a881-b93452382078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>overflow-hidden opacity-60</value>
      <webElementGuid>26138bd6-712c-4422-a9f6-d5e4e65d8165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select item...</value>
      <webElementGuid>fd99572c-e8c9-40d2-bd16-fa100ecb501a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;courseIntention&quot;)/span[@class=&quot;overflow-hidden opacity-60&quot;]</value>
      <webElementGuid>97a440c1-004d-4d08-94b9-51d8a323c7ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='courseIntention']/span</value>
      <webElementGuid>047b276f-8ccd-4f56-a0ea-ec65e017838d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mandarin'])[1]/following::span[2]</value>
      <webElementGuid>d4e6e58b-9098-4fc7-9684-2a968b7858a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/button/span</value>
      <webElementGuid>1a75de2c-dea0-46eb-b4f2-1c94e5a06b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select item...' or . = 'Select item...')]</value>
      <webElementGuid>d225a0c1-b6e4-4950-b3be-f4e71ae24c6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
