<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_0 Filter yang diterapkan</name>
   <tag></tag>
   <elementGuidId>82a0ed51-0508-4940-aa41-7ddf9ef53fbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;radix-_r_3i_&quot;]/div[1]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.items-center.justify-between.gap-3 > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-_r_2g5_']/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;0 Filter yang diterapkan&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9879d47f-cb27-4448-9b56-7609c4a03327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0 Filter yang diterapkan</value>
      <webElementGuid>888f039b-3f74-46b0-88c7-9ff74d13a807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;radix-_r_3i_&quot;]/div[1]/p</value>
      <webElementGuid>06374fd2-edd6-4900-a55b-ccaee4152209</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-_r_2g5_']/div/p</value>
      <webElementGuid>e76a30d0-fb6f-47bf-918d-c53556a1f1fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::p[1]</value>
      <webElementGuid>c03949e7-c1e4-493f-b4bc-e9646ae0a261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus Filter'])[1]/preceding::p[1]</value>
      <webElementGuid>eb879c43-1608-48e0-b565-f699e957a49a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kursus - Angkatan'])[3]/preceding::p[2]</value>
      <webElementGuid>065c5363-66e6-4617-adc0-d6f34585bead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0 Filter yang diterapkan']/parent::*</value>
      <webElementGuid>ffed89a8-688c-4fe5-993d-9d68b989ec29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/p</value>
      <webElementGuid>02097945-b7f0-4a31-865e-736adc6d93d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '0 Filter yang diterapkan' or . = '0 Filter yang diterapkan')]</value>
      <webElementGuid>0331aada-d1fb-46f2-86c7-afcf74777959</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
