<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tanggal</name>
   <tag></tag>
   <elementGuidId>82fc32ba-93bc-46d4-9886-101c76dc619f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.truncate.opacity-60</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='date']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Date picker&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d096cbd9-f7db-4c79-9d28-ea578e5172a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>truncate opacity-60</value>
      <webElementGuid>6ebb3bba-e0b7-40e3-b79b-d807ab069def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tanggal</value>
      <webElementGuid>a6d2128d-a7ec-4406-bbe7-2a9d35093219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;date&quot;)/span[@class=&quot;truncate opacity-60&quot;]</value>
      <webElementGuid>d7fb0811-1586-4a96-a412-7f532d194d35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='date']/span</value>
      <webElementGuid>274cc490-9f0e-47d8-b220-9d83cd6863b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Jadwal'])[1]/preceding::span[2]</value>
      <webElementGuid>e7e93d3f-7f07-4d83-b27d-05f0849dc7ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button/span</value>
      <webElementGuid>65a7d570-ea56-44cc-9240-2a2511c735f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tanggal' or . = 'Tanggal')]</value>
      <webElementGuid>63801fd2-d6b9-42ca-b390-7382ead21f76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
