<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pilih mess</name>
   <tag></tag>
   <elementGuidId>901bd663-38e5-413c-9d35-eed71d7826cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radix-_r_298_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-_r_298_']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;radix-_r_80_&quot;][count(. | //div[@data-slot = 'command-item' and @class = concat(&quot;data-[selected=true]:bg-accent data-[selected=true]:text-accent-foreground [&amp;_svg:not([class*=&quot; , &quot;'&quot; , &quot;text-&quot; , &quot;'&quot; , &quot;])]:text-muted-foreground relative flex cursor-default items-center gap-2 rounded px-2 py-1.5 text-[93.75%] outline-hidden select-none data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg]:shrink-0 [&amp;_svg:not([class*=&quot; , &quot;'&quot; , &quot;size-&quot; , &quot;'&quot; , &quot;])]:size-4&quot;) and @id = 'radix-_r_298_' and @role = 'option' and @aria-disabled = 'false' and @aria-selected = 'true' and @data-disabled = 'false' and @data-selected = 'true']) = count(//div[@data-slot = 'command-item' and @class = concat(&quot;data-[selected=true]:bg-accent data-[selected=true]:text-accent-foreground [&amp;_svg:not([class*=&quot; , &quot;'&quot; , &quot;text-&quot; , &quot;'&quot; , &quot;])]:text-muted-foreground relative flex cursor-default items-center gap-2 rounded px-2 py-1.5 text-[93.75%] outline-hidden select-none data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg]:shrink-0 [&amp;_svg:not([class*=&quot; , &quot;'&quot; , &quot;size-&quot; , &quot;'&quot; , &quot;])]:size-4&quot;) and @id = 'radix-_r_298_' and @role = 'option' and @aria-disabled = 'false' and @aria-selected = 'true' and @data-disabled = 'false' and @data-selected = 'true'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Mess Sigra Kamar D05&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>af332a61-a983-4da8-9284-a34a0ffa1251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>command-item</value>
      <webElementGuid>cfaed10b-ae2a-4621-a032-ade4770e562b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>data-[selected=true]:bg-accent data-[selected=true]:text-accent-foreground [&amp;_svg:not([class*='text-'])]:text-muted-foreground relative flex cursor-default items-center gap-2 rounded px-2 py-1.5 text-[93.75%] outline-hidden select-none data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg]:shrink-0 [&amp;_svg:not([class*='size-'])]:size-4</value>
      <webElementGuid>b3351206-4cc4-45f8-9712-7e191db7f5df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-_r_298_</value>
      <webElementGuid>60c64cc1-8702-4ef9-a10a-8fd4207ba53e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>a7c2e687-dddf-4cca-b4b4-c05b2c3b0356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4636f7c8-611f-4463-a899-27e3ce87cfc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0ae44424-6966-4af4-bcd2-687ee9313f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f98a5fee-85b1-4106-b740-9f9a4c046ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5145a2bd-727f-4307-80e4-061e26d300e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>525</value>
      <webElementGuid>621a2798-0fef-4003-9c45-196ecd4a5498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mess Sigra Kamar D05</value>
      <webElementGuid>b517a9b5-d74d-4c88-bfbd-d2f7adcf3121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;radix-_r_80_&quot;]</value>
      <webElementGuid>521f040c-73d8-4edb-b6a3-d1306c460fa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='radix-_r_298_']</value>
      <webElementGuid>24aee4ee-193e-4699-b4e2-943fbd2ccb77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-_r_293_']/div/div/div/div</value>
      <webElementGuid>49392e92-312d-457d-a1ff-e7e5da28d7a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[9]</value>
      <webElementGuid>2380fad6-b20f-4f57-b882-db2c725408d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mess Sigra Kamar D10'])[1]/preceding::div[1]</value>
      <webElementGuid>ccd317f3-4203-44ed-b642-42f59eaa61b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mess Wan Kamar 102'])[1]/preceding::div[2]</value>
      <webElementGuid>055ff76e-738d-4436-8008-157fc82bf826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mess Sigra Kamar D05']/parent::*</value>
      <webElementGuid>e63cd7ea-6277-48ac-bf04-2284d01037e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div</value>
      <webElementGuid>70bee70a-3544-40fd-9fa1-c8c997d27f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'radix-_r_298_' and (text() = 'Mess Sigra Kamar D05' or . = 'Mess Sigra Kamar D05')]</value>
      <webElementGuid>628ba92d-d8b3-4657-9f45-6befe78fc196</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
