<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih Tanggal lahir</name>
   <tag></tag>
   <elementGuidId>0ac0b4ed-4726-4bb6-bba0-e0a4a3e26fdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.truncate.opacity-60</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='dateOfBirth']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Date picker&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>83cacea9-b4aa-4132-97c2-cd38b8ed0b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>truncate opacity-60</value>
      <webElementGuid>18ef3c80-46c9-4907-a3c3-85536223fa05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Tanggal</value>
      <webElementGuid>37cd12fd-d51a-48ab-a1dd-637eedab2b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dateOfBirth&quot;)/span[@class=&quot;truncate opacity-60&quot;]</value>
      <webElementGuid>b5dd0b8d-71d3-48f0-b5ac-1a506f3d7908</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='dateOfBirth']/span</value>
      <webElementGuid>9591a686-cba3-476e-a466-e167bb447c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pilih Tanggal']/parent::*</value>
      <webElementGuid>287a22dd-df6a-4045-942e-aa6f0fdd0aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/button/span</value>
      <webElementGuid>dd384b3c-b7e5-4087-ba98-ddb4731f1453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Pilih Tanggal' or . = 'Pilih Tanggal')]</value>
      <webElementGuid>e49ae652-d4f3-4b4c-90a3-6d7a158c085b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
