<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select item ruangan</name>
   <tag></tag>
   <elementGuidId>c03a392b-7b7e-4518-b08b-2305101dbea7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.overflow-hidden.opacity-60</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='room']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Ruangan*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4cb744e7-55fd-4911-a895-1de08a81dc4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>overflow-hidden opacity-60</value>
      <webElementGuid>bf2bea08-f431-4248-83bb-ced4f9c711b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select item...</value>
      <webElementGuid>d1ba576d-3afb-45e2-bbb9-40f05fc6c6b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;room&quot;)/span[@class=&quot;overflow-hidden opacity-60&quot;]</value>
      <webElementGuid>27f7b1a1-47dd-4831-bb58-48388e36ff1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='room']/span</value>
      <webElementGuid>c39dd1c9-9a3f-47f1-998b-66e3e022a951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nasional'])[1]/following::span[2]</value>
      <webElementGuid>cf9eb591-9de4-40cd-929b-372c0136f41c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciri Fisik'])[1]/preceding::span[1]</value>
      <webElementGuid>99d15122-bed5-40f9-9455-deea20e9acef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ukuran Seragam'])[1]/preceding::span[1]</value>
      <webElementGuid>3f4b5f2d-10d5-4bdc-b5d0-cd94f27b8886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select item...']/parent::*</value>
      <webElementGuid>748c09b9-cd25-43aa-b356-92269688bd74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/button/span</value>
      <webElementGuid>92665607-2446-48bf-89e0-a37d142994d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select item...' or . = 'Select item...')]</value>
      <webElementGuid>971f5707-099b-49e4-8a92-973c51ff918e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
