<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>delete</name>
   <tag></tag>
   <elementGuidId>993079a7-50f2-4c65-a45d-39a62a77def2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='deleteEntry(this)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>90faff6b-6770-4d58-8fa2-7763aaee97ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>d97a290a-e70f-4044-be4f-d36ba6190db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>deleteEntry(this)</value>
      <webElementGuid>2ca6c221-cec9-4d27-bf07-2df0ceea1f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-route</name>
      <type>Main</type>
      <value>https://portal-badiklat.kemhan.go.id/users/13aa1540-f1c6-4235-ae82-89122df55a5f</value>
      <webElementGuid>6bbcb62c-d0ce-46fc-9d7c-929e695ac27d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Hapus Sistem Pengelolaan Informasi Akun</value>
      <webElementGuid>d8e98dda-8516-49c6-bde2-ce0cd6388d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-icons</value>
      <webElementGuid>a5a94af0-af10-48d0-ad61-3bcf6bf71e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-button-type</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>03e3c6bb-4cda-4c21-9baf-52638cb9d95f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;crudTable&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[6]/a[@class=&quot;btn btn-icons&quot;]</value>
      <webElementGuid>3ce82b0e-6c9a-49a2-97ce-3d7698c6c373</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='deleteEntry(this)']</value>
      <webElementGuid>7c026c46-d4f6-44ac-9892-8c0a4201289f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='crudTable']/tbody/tr/td[6]/a[2]</value>
      <webElementGuid>e671984b-a80c-4a71-b2b5-c45b52f552bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='siswa'])[1]/following::a[2]</value>
      <webElementGuid>f26d02dd-62fe-44fa-81c4-ab404ab7d83b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pusdiklat Bahasa Badiklat Kemhan'])[2]/following::a[2]</value>
      <webElementGuid>b7eac95f-2f7e-4ec9-ab9e-c5b8d88b0d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>f0f1317b-4454-4c96-8545-d209deab0c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a[2]</value>
      <webElementGuid>9df19c88-aa7a-4dad-9ab6-6ec718163755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @title = 'Hapus Sistem Pengelolaan Informasi Akun']</value>
      <webElementGuid>0b98665f-fc72-46cb-9b8e-ff3a2a567710</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
