<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edit</name>
   <tag></tag>
   <elementGuidId>09d4aed2-32ce-4d9d-9b98-3ed87abee953</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick='InlinePopup(this)'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-icons.btn-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Ubah Sistem Pengelolaan Informasi Akun&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>be4cbe7f-a2f4-4d4f-a4e9-db841f15395f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ubah Sistem Pengelolaan Informasi Akun</value>
      <webElementGuid>9e9f0a81-4ad0-48cc-b1fd-d22f09a87935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>InlinePopup(this)</value>
      <webElementGuid>5c10cb32-1ab5-4313-9122-83400a7d82f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popup-route</name>
      <type>Main</type>
      <value>https://portal-badiklat.kemhan.go.id/users</value>
      <webElementGuid>143d0dcf-34fc-4924-98c9-40f09f881897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent-loaded-fields</name>
      <type>Main</type>
      <value>[]</value>
      <webElementGuid>62b8cc62-c545-4d80-9721-77ce71266aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field-related-name</name>
      <type>Main</type>
      <value>Akun</value>
      <webElementGuid>d33c219a-cdf9-4b84-afa3-2da166a40f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popup-id</name>
      <type>Main</type>
      <value>13aa1540-f1c6-4235-ae82-89122df55a5f</value>
      <webElementGuid>72274ae8-5354-4f0d-9e94-137766201ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-icons btn-link</value>
      <webElementGuid>1aedc4dd-7856-433f-b8b4-2aff7783c69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;crudTable&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[6]/a[@class=&quot;btn btn-icons btn-link&quot;]</value>
      <webElementGuid>661846b9-b665-4953-be73-c524bc4a1653</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='InlinePopup(this)'])[2]</value>
      <webElementGuid>7fcd3be6-9bcf-40c8-b114-cff6a505458a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='crudTable']/tbody/tr/td[6]/a[3]</value>
      <webElementGuid>aeea9ad7-9e03-439d-9b23-ddeb8e52c530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='siswa'])[1]/following::a[3]</value>
      <webElementGuid>4dd10cc1-3aec-41a3-89ce-27e5a8a34f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pusdiklat Bahasa Badiklat Kemhan'])[2]/following::a[3]</value>
      <webElementGuid>748feede-5689-4d3f-a3ab-beb191fae132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a[3]</value>
      <webElementGuid>c965944b-ea98-4cad-8c26-c2c35b2ac338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Ubah Sistem Pengelolaan Informasi Akun']</value>
      <webElementGuid>252bff12-f7b8-4f13-83f2-2c611a82e785</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
