<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Testing_btn btn-icons</name>
   <tag></tag>
   <elementGuidId>d63fe19f-7f87-4e52-a03d-16ab7b5e3e6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='deleteEntry(this)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-icons</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>18be42fb-3df3-47e7-b32b-8ba16bf7068b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>8d2b14a3-6596-49fd-b72e-c4827c614850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>deleteEntry(this)</value>
      <webElementGuid>aa8ccde7-f4f2-4c62-88e8-e4a4748f4403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-route</name>
      <type>Main</type>
      <value>https://portal-badiklat.kemhan.go.id/kalender-akademik/493</value>
      <webElementGuid>fed7c2ff-6c6b-40f6-89e7-125a6a87e193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-icons</value>
      <webElementGuid>947fbc4c-e57a-4149-8941-fce28fa5d790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-button-type</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>cf714b56-2a1b-47b9-9ed4-38e79b1c6520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Hapus Pengelolaan Informasi Kalender Akademik</value>
      <webElementGuid>6e450166-dac1-4719-a4ca-cf6935fb1fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;app flex-row align-items-center&quot;]/div[@class=&quot;animated fadeIn&quot;]/div[@class=&quot;row calendar-wrapper&quot;]/div[@class=&quot;col-md-5 wrapper-detail&quot;]/div[@class=&quot;list-detail&quot;]/div[@class=&quot;mt-3 calender-card-wrapper&quot;]/div[@class=&quot;calender-card&quot;]/div[2]/a[@class=&quot;btn btn-icons&quot;]</value>
      <webElementGuid>96e700e6-3bc5-4869-8996-0081e8bc77a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Kalender Akademik/Page_SISTEM INFORMASI AKADEMIK/Page_SISTEM INFORMASI AKADEMIK/iframe_Kalender Akademik_min-h-calc(100vh-12rem) w-full</value>
      <webElementGuid>1b8261e6-9af6-44aa-ba41-10bc517e60bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='deleteEntry(this)']</value>
      <webElementGuid>074a13d9-5601-4f48-8407-0c6c2fd30fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testing'])[1]/following::a[1]</value>
      <webElementGuid>3e3c7ba0-332d-4a47-9563-27d8b7ad3d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Senin, 27 April 2026'])[1]/following::a[1]</value>
      <webElementGuid>b7671034-2d9c-42a7-9fad-7fc86b33dd0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>6e659299-c309-48a0-9c3c-2e54e78f3694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>c96422df-d7db-462f-aaca-4017f1089526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @title = 'Hapus Pengelolaan Informasi Kalender Akademik']</value>
      <webElementGuid>bb78c11d-1d5e-49a8-a78c-5cabc124bec0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
