<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sampai_to_date</name>
   <tag></tag>
   <elementGuidId>ebca9dd3-3b59-4ee2-81f5-ea32d1c34472</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='to_date']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;to_date&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;to_date&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5d1f05d-7605-4b13-ae18-56cc9722635b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>datetime-local</value>
      <webElementGuid>b31a9a30-10d8-44c6-b4d0-a33fa1d97f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>to_date</value>
      <webElementGuid>ec0c7a0f-cfce-4e66-9ada-37d105bb8f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>75607934-4dee-4d16-a15b-6f98f2dab8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Kalender Akademik-inline-create-form&quot;)/div[@class=&quot;wrapper-inline&quot;]/div[@class=&quot;card-body row&quot;]/div[@class=&quot;form-group col-sm-12 required&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>543987d5-0b76-44bc-b4d3-b77257bb183a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Kalender Akademik/Page_SISTEM INFORMASI AKADEMIK/iframe_Kalender Akademik_min-h-calc(100vh-12rem) w-full</value>
      <webElementGuid>6f09a11c-fa2c-4691-be95-a3c366afc210</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='to_date']</value>
      <webElementGuid>e269d7ce-fcfd-4e29-880c-932c41acb0ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Kalender Akademik-inline-create-form']/div/div/div[3]/input</value>
      <webElementGuid>bea009d2-34db-4a98-b3b2-8f895afa1882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>9a28e85b-68b6-4250-b5f6-8c8f8bfbf823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'datetime-local' and @name = 'to_date']</value>
      <webElementGuid>e68dc61b-4c56-4a74-a858-13008b85d7f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
