<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tambah</name>
   <tag></tag>
   <elementGuidId>7bb4dba6-1d49-494a-a105-c045b43432aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Desember'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.add-btn-calendar > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Tambah&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8eddd915-04b8-4d9b-a73b-a19d10a06ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Tambah
            </value>
      <webElementGuid>10023392-0257-459d-ba04-54cc657689e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;app flex-row align-items-center&quot;]/div[@class=&quot;animated fadeIn&quot;]/div[@class=&quot;row calendar-wrapper&quot;]/div[@class=&quot;col-md-5 wrapper-detail&quot;]/div[@class=&quot;calender__action&quot;]/div[@class=&quot;add-btn-calendar&quot;]/span[1]</value>
      <webElementGuid>69fbcf91-4699-4e97-bf46-52b44874f0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Kalender Akademik/Page_SISTEM INFORMASI AKADEMIK/iframe_Kalender Akademik_min-h-calc(100vh-12rem) w-full</value>
      <webElementGuid>fac6bef5-1bd3-4de9-b853-5f6cc54ae25f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desember'])[1]/following::span[1]</value>
      <webElementGuid>bf66f52c-e474-4499-9d16-6c81dabb7a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='November'])[1]/following::span[1]</value>
      <webElementGuid>65a78859-0551-463f-9c1a-cec413557e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengelolaan Informasi Kalender Akademik'])[1]/preceding::span[1]</value>
      <webElementGuid>9d53ca87-e94f-49cf-9489-6e3999852580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Senin, 27 April 2026'])[1]/preceding::span[1]</value>
      <webElementGuid>a8fcb2a8-e6ac-441a-849f-8f6768db9df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tambah']/parent::*</value>
      <webElementGuid>0b74f6e4-3c91-4615-a147-3aeb8ef78d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span</value>
      <webElementGuid>93237f05-fd0e-4025-ba4d-46a1716a3d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
            Tambah
            ' or . = '
            Tambah
            ')]</value>
      <webElementGuid>5026fe81-1559-4fcc-8ff0-432a30c71639</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
