<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Penilaian</name>
   <tag></tag>
   <elementGuidId>f5bf950b-42dd-4f3b-9b0a-4e7d80be295c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='radix-_r_1e_']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4984d234-2978-4f17-b21e-3447c1fe9bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>[[data-collapsible][data-state=collapsed]_&amp;]:opacity-0</value>
      <webElementGuid>ecb9e6a8-9cc8-47c2-9ef7-5f12f06ba3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Penilaian</value>
      <webElementGuid>6ca64ca1-3101-451a-b86f-3b871ede3976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-_r_1e_&quot;)/span[@class=&quot;[[data-collapsible][data-state=collapsed]_&amp;]:opacity-0&quot;]</value>
      <webElementGuid>a8ac4498-f059-4ef5-b769-c69c2d799434</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='radix-_r_1e_']/span</value>
      <webElementGuid>1038a11b-160f-4475-96bc-e3604e52d8c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jadwal Mingguan'])[1]/following::span[1]</value>
      <webElementGuid>7ddb28be-9737-4c86-b010-d46339f95816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jadwal Ujian Masuk'])[1]/following::span[2]</value>
      <webElementGuid>95107ff2-6a99-4cc8-9d8c-99e3afda4ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penilaian Nilai Akhir'])[1]/preceding::span[1]</value>
      <webElementGuid>97014694-c79d-4da0-a072-ece575e591dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sertifikat Kelulusan'])[1]/preceding::span[2]</value>
      <webElementGuid>a4581ed1-7d34-4b0e-a03e-85493c45f4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Penilaian']/parent::*</value>
      <webElementGuid>b171a673-d47b-42e6-8b1a-0299fe28043c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/button/span</value>
      <webElementGuid>6d9f9c89-b7ec-42db-80c6-c3e37a2f952d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Penilaian' or . = 'Penilaian')]</value>
      <webElementGuid>17be3c1d-7cb5-42b5-b94c-8f65f8418168</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
