<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Subjek</name>
   <tag></tag>
   <elementGuidId>f5190cf1-88da-4965-9d25-20b5b5269405</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Bahasa'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>11e3f6a0-9e13-4e57-aa4a-404b9b27ed8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subjek</value>
      <webElementGuid>2d7c307a-8fc3-4ab0-861e-3bda852c4a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;roboto_d0e8d990-module__AH7_Na__className text-base antialiased&quot;]/div[@class=&quot;group/sidebar-wrapper has-data-[variant=inset]:bg-sidebar flex min-h-screen w-full grow&quot;]/aside[@class=&quot;group peer text-sidebar-foreground relative hidden md:sticky md:top-0 md:block md:max-h-screen&quot;]/div[@class=&quot;absolute inset-y-0 z-10 hidden h-full w-(--sidebar-width) transition-[left,right,width] duration-200 ease-linear md:flex left-0 group-data-[collapsible=offcanvas]:left-[calc(var(--sidebar-width)*-1)] group-data-[collapsible=icon]:w-(--sidebar-width-icon) group-data-[side=left]:border-r group-data-[side=right]:border-l&quot;]/div[@class=&quot;bg-sidebar group-data-[variant=floating]:border-sidebar-border flex h-full w-full flex-col group-data-[variant=floating]:rounded-lg group-data-[variant=floating]:border group-data-[variant=floating]:shadow-sm&quot;]/div[@class=&quot;flex flex-1 flex-col overflow-auto group-data-[collapsible=icon]:overflow-hidden&quot;]/div[@class=&quot;relative flex w-full min-w-0 flex-col p-5 overflow-y-auto&quot;]/ul[@class=&quot;flex w-full min-w-0 flex-col gap-0.5&quot;]/li[@class=&quot;group/menu-item relative&quot;]/button[@class=&quot;peer/menu-button flex w-full overflow-hidden p-3 text-left outline-hidden ring-sidebar-ring transition-[width,height,padding] focus-visible:bg-foreground/5 active:bg-sidebar-accent active:text-sidebar-accent-foreground disabled:pointer-events-none disabled:opacity-50 group-has-data-[sidebar=menu-action]/menu-item:pr-8 aria-disabled:pointer-events-none aria-disabled:opacity-50 data-[active=true]:bg-sidebar-accent data-[active=true]:font-medium data-[active=true]:text-sidebar-accent-foreground data-[state=open]:hover:bg-sidebar-accent data-[state=open]:hover:text-sidebar-accent-foreground group-data-[collapsible=icon]:size-11 group-data-[collapsible=icon]:p-3 [&amp;>span:last-child]:truncate [&amp;>svg]:size-5 [&amp;>svg]:shrink-0 text-base hover:bg-sidebar-accent hover:text-sidebar-accent-foreground h-fit items-center rounded-sm leading-5.25 group-data-[state=expanded]:min-h-11.25 [&amp;>span:last-child]:whitespace-normal data-[active=true]:bg-primary! data-[active=true]:text-primary-foreground! [&amp;_svg:not([class*=&quot;text-&quot;])]:opacity-60 gap-3&quot;]/span[1]</value>
      <webElementGuid>cd4d32e9-ad28-4df1-add2-a34efd26ed1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bahasa'])[1]/following::span[1]</value>
      <webElementGuid>4e0c3a5f-65f3-4bc3-ac1f-b4d5ebe253f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kalender Akademik'])[1]/following::span[2]</value>
      <webElementGuid>52f35de7-9754-46c7-af32-a224c8f6f21b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kursus'])[1]/preceding::span[1]</value>
      <webElementGuid>47739a02-bb49-45e2-afbf-570080c5c09d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelas'])[1]/preceding::span[2]</value>
      <webElementGuid>b6deba49-b58d-438c-88b0-cfa9f414dbfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Subjek']/parent::*</value>
      <webElementGuid>505d10b7-d563-4af9-b634-ba22ac4f0ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/button/span</value>
      <webElementGuid>ae0af3f8-b824-4a51-8a54-6c00249e40d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Subjek' or . = 'Subjek')]</value>
      <webElementGuid>1de532e7-e2e2-43c8-9225-096554059ff1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
