<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Akses</name>
   <tag></tag>
   <elementGuidId>65eb7da2-9dd9-4750-8aea-e0a78c1efd67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-_r_1n_']/div/button[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b251cb2b-d1c4-421a-867e-c51ad1ed73cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Akses</value>
      <webElementGuid>95deab68-a700-4e76-8ceb-aa2cd09bd3e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-_r_1n_&quot;)/div[@class=&quot;pl-8 *:mt-1 group-data-[state=collapsed]:hidden in-data-[has-valid-root-path=&quot;true&quot;]:hidden&quot;]/button[@class=&quot;peer/menu-button flex w-full overflow-hidden p-3 text-left outline-hidden ring-sidebar-ring transition-[width,height,padding] focus-visible:bg-foreground/5 active:bg-sidebar-accent active:text-sidebar-accent-foreground disabled:pointer-events-none disabled:opacity-50 group-has-data-[sidebar=menu-action]/menu-item:pr-8 aria-disabled:pointer-events-none aria-disabled:opacity-50 data-[active=true]:bg-sidebar-accent data-[active=true]:font-medium data-[active=true]:text-sidebar-accent-foreground data-[state=open]:hover:bg-sidebar-accent data-[state=open]:hover:text-sidebar-accent-foreground group-data-[collapsible=icon]:size-11 group-data-[collapsible=icon]:p-3 [&amp;>span:last-child]:truncate [&amp;>svg]:size-5 [&amp;>svg]:shrink-0 text-base hover:bg-sidebar-accent hover:text-sidebar-accent-foreground h-fit items-center rounded-sm leading-5.25 group-data-[state=expanded]:min-h-11.25 [&amp;>span:last-child]:whitespace-normal data-[active=true]:bg-primary! data-[active=true]:text-primary-foreground! [&amp;_svg:not([class*=&quot;text-&quot;])]:opacity-60 gap-3&quot;]/span[1]</value>
      <webElementGuid>fe653f5f-b139-44c1-9bbe-3146a1034dba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-_r_1n_']/div/button[2]/span</value>
      <webElementGuid>8dc38cf6-1a44-4ebb-adf7-8cb33166bcac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peran &amp; Izin'])[1]/following::span[1]</value>
      <webElementGuid>83a70492-f083-4dce-8b15-14e048bb4e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manajemen Akun'])[1]/following::span[2]</value>
      <webElementGuid>46f32624-a169-474b-a0da-bc0341fedb09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SU'])[1]/preceding::span[1]</value>
      <webElementGuid>5f0f93af-35f9-423c-8ffb-b629a94e6e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='superadmin'])[1]/preceding::span[3]</value>
      <webElementGuid>abbaeb76-4f90-4162-8b12-4c6f35ea947a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Akses']/parent::*</value>
      <webElementGuid>ae5dc234-a037-4605-80d5-d037c7495e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[15]/div/div/div/div/button[2]/span</value>
      <webElementGuid>eb037f1e-3946-4d2c-a2ad-ed97a5e2e062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Akses' or . = 'Akses')]</value>
      <webElementGuid>33e63339-25bd-47a1-9e2b-d3aa95b0fc1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
