<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Penilaian</name>
   <tag></tag>
   <elementGuidId>f5bf950b-42dd-4f3b-9b0a-4e7d80be295c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='radix-_r_1e_']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[(text() = 'Penilaian' or . = 'Penilaian')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ed7370a5-cf19-4621-8dfe-4a26ffbc99d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>[[data-collapsible][data-state=collapsed]_&amp;]:opacity-0</value>
      <webElementGuid>056f0e33-3360-4b01-9c4d-90440f96ffe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Penilaian</value>
      <webElementGuid>cc51f427-935f-4df7-9753-0ca48eede340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-_r_1e_&quot;)/span[@class=&quot;[[data-collapsible][data-state=collapsed]_&amp;]:opacity-0&quot;]</value>
      <webElementGuid>6e852515-531d-4e33-a72b-4f2028d57cfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='radix-_r_1e_']/span</value>
      <webElementGuid>b401aed1-4773-4c2d-9fa5-e74bd3828889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jadwal Mingguan'])[1]/following::span[1]</value>
      <webElementGuid>39af61ad-3bff-43be-a443-d19f17d6bf62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jadwal Ujian Masuk'])[1]/following::span[2]</value>
      <webElementGuid>0eef4df3-0673-4d1c-91f7-2f8a9e3464ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penilaian Nilai Akhir'])[1]/preceding::span[1]</value>
      <webElementGuid>4ac4d727-4f74-42e9-bdd8-bbed04101f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sertifikat Kelulusan'])[1]/preceding::span[2]</value>
      <webElementGuid>e30b7b31-acc6-4760-b503-f9a27fa57250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Penilaian']/parent::*</value>
      <webElementGuid>99f80c67-c88b-4b6c-94fd-193c9c64377e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/button/span</value>
      <webElementGuid>c6b0d8ef-d6d0-4072-8ecc-191dc1859e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Penilaian' or . = 'Penilaian')]</value>
      <webElementGuid>a150f4bc-cb03-4da1-896a-097aa5f7f4e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
