<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tanggal Mulai</name>
   <tag></tag>
   <elementGuidId>836b35f9-03fa-47f8-8b2b-080b4f7e61a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='openDate']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.truncate.opacity-60</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#openDate</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e43ded20-6bb4-4902-a110-2081dbeffa01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>truncate opacity-60</value>
      <webElementGuid>88134fd3-12c7-456d-a78f-191f6e71956e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tanggal Mulai</value>
      <webElementGuid>31239605-2c29-4683-9ac1-8beefb349c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;openDate&quot;)/span[@class=&quot;truncate opacity-60&quot;]</value>
      <webElementGuid>cedfca13-6036-4476-a301-16a5aa6d2db9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='openDate']/span</value>
      <webElementGuid>2267ce0c-a7e4-439d-83fe-d971e5aef19d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Akhir'])[2]/preceding::span[2]</value>
      <webElementGuid>114e4b6a-a126-4eee-9866-412be0cc38c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div[2]/button/span</value>
      <webElementGuid>be9f847f-3972-4dee-96e9-e4bf7e81a987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tanggal Mulai' or . = 'Tanggal Mulai')]</value>
      <webElementGuid>0edaebbc-4c9c-4f8b-b7be-7e15281bd010</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
