<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_2 Filter yang diterapkan</name>
   <tag></tag>
   <elementGuidId>33d71a47-2812-4f9a-a207-961d09752f93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-_r_jj_']/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.items-center.justify-between.gap-3 > p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div/div[1]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;2 Filter yang diterapkan&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>8987073e-7754-48e8-bda6-bdb64a9b852e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2 Filter yang diterapkan</value>
      <webElementGuid>aa67d5c8-1fac-446f-999f-0805b2dbf354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div/div[1]/p</value>
      <webElementGuid>6fa5ea13-a319-40ec-b13a-b675f4be011d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-_r_jj_']/div/p</value>
      <webElementGuid>7f8895c6-9fcd-4422-8712-260e657ac713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menampilkan 1 hingga 1 dari 1 data'])[1]/following::p[1]</value>
      <webElementGuid>9d7d3d83-c476-429d-a8b5-39fe6318aab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus Filter'])[1]/preceding::p[1]</value>
      <webElementGuid>7e28da6f-371e-41e9-9745-e6fc299f3d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kursus Mandarin - Angkatan Mandarin'])[2]/preceding::p[2]</value>
      <webElementGuid>09f5b042-b394-4cab-ae32-b76ec6d40ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2 Filter yang diterapkan']/parent::*</value>
      <webElementGuid>ef0ff1eb-c01c-41d3-8af0-1f3729b013b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/p</value>
      <webElementGuid>87fc5f53-a00d-414e-a5cd-67bad1f13abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '2 Filter yang diterapkan' or . = '2 Filter yang diterapkan')]</value>
      <webElementGuid>5d1a9354-38a4-42e9-bf03-539e329e9ed7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
